apiVersion: v1
kind: Namespace
metadata:
  name: nginx-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx-demo
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          return 200 "Hello from NGINX on node: $hostname\n";
        }
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-on-each-node
  namespace: nginx-demo
spec:
  selector:
    matchLabels:
      app: nginx-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-node
    spec:
      # This toleration lets the pod run on control-plane nodes only if they are schedulable.
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: nginx-demo
spec:
  type: NodePort
  selector:
    app: nginx-node
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080

