apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql
  labels:
    app: psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - name: psql
        image: postgres
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
        ports:
        - containerPort: 5332
